In [42]:
import numpy as np
import math
#数据集
from sklearn.datasets import load_iris
#划分训练和测试集
from sklearn.model_selection import train_test_split

import matplotlib as mlp
mlp.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from mpl_toolkits.mplot3d import axes3d, Axes3D


In [43]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [44]:
type(iris)

sklearn.utils.Bunch

In [45]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [46]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [48]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [49]:
class Perception(object):
	"""docstring for Perception"""
	def __init__(self, eta=0.01, n_iter=20):
		self.eta = eta
		self.n_iter = n_iter
	
	def fit(self, X, y):
		print(X.shape[1])
		self.wb = np.zeros(1 + X.shape[1])
		self.theta1 = []
		self.theta2 = []
		self.errors_ = []
		i = 0
		for i in range(self.n_iter):
			i += 1
			errors = 0
			for xi , yi in zip(X, y):
				update = self.eta * (yi - self.predict(xi))
				self.wb[1:] += update * xi
				self.wb[0] += update
				errors += int(update != 0.0)
				err_sum = 0
				for xj, yj in zip(X, y):
					if (yj - self.predict(xj) != 0):
						err_sum += abs(yj - self.predict(xj))
			self.theta1.append(self.wb[1])
			self.theta2.append(self.wb[2])
			self.errors_.append(errors)
		print (self.wb)
		return self

	def net_input (self, xi):
		return np.dot(xi, self.wb[1:]) + self.wb[0]

	def predict(self, xi):
		return np.where(self.net_input(xi) <= 0.0, -1, 1)

	def plot_decision_regions(self, X, y, resolution=0.02):
		colors= ['red', 'blue']
		markers = ['o', 'x']
		cmap = ListedColormap(colors[:len(np.unique(y))])

		x1_max, x1_min = max(X[:, 0]) + 1, min(X[:,0]) -1
		x2_max, x2_min = max(X[:, 1]) + 1, min(X[:,1]) -1
        
		xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution), np.arange(x2_min, x2_max, resolution))

		Z = self.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
		print ("Z is:", Z)
		Z = Z.reshape(xx1.shape)
		plt.xlim(xx1.min(), xx1.max())
		plt.ylim(xx2.min(), xx2.max())

		for idx,cl in enumerate(np.unique(y)):
#			print(idx, cl)
			plt.scatter(x=X[y == cl, 0], y=X[y == cl, 1], alpha=.4, cmap=cmap(idx), marker=markers[idx], label=cl)

		plt.show()
		plt.savefig('./perception.png', format='png')


	def painter3D(self, theta1, theta2, loss, XX, YY):
		fig = plt.figure()
		ax1 = Axes3D(fig)
		x,y,z = theta1, theta2, loss
		XXY = XX
		lst = []
        
		xa, ya = np.meshgrid(np.arange(-10, 10, 0.5), np.arange(-10, 10, 0.5))
		sum = xa - xa
        
		for k in range(0, XXY.shape[0], 1):
			sum += np.exp(YY[k] - (xa * XXY[k][0] + ya*XXY[k][1]))

		ax1.plot_surface(xa, ya, sum, rstride=1, cstride=1, cmap=plt.cm.jet,alpha= 0.3)
		ax1.plot_wireframe(x,y,z, rstride=5, cstride=5)
		ax1.set_xlabel("theta1")
		ax1.set_ylabel("theta2")
		ax1.set_zlabel("loss")
		plt.show()
		plt.savefig('./perception.sgd.png', format='png')



In [50]:
X = iris.data[:100, [0,1]]
y = iris.target[:100]
y = np.where(y ==1, 1, -1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)
ppn = Perception(eta = 0.1, n_iter=19)

In [51]:
rst  = ppn.fit(X_train, y_train)

2
[-2.    5.3  -8.24]


In [52]:
# ppn.painter3D(np.array(rst.theta1).reshape(len(rst.theta1), 1), np.array(rst.theta2).reshape(len(rst.theta2), 1), np.array(rst.errors_).reshape(len(rst.errors_), 1),X,y)

In [53]:
ppn.plot_decision_regions(X_test, y_test)

Z is: [ 1  1  1 ... -1 -1 -1]


AttributeError: 'NoneType' object has no attribute 'sqrt'